import type { ActiveTargets, CareerTarget, TargetJob, TargetJobStatus } from "../domain/types.js";
import { FileWorkspace } from "../infrastructure/filesystem/file-workspace.js";
import { newId, nowIso } from "../shared/utils.js";

const terminal = new Set<TargetJobStatus>(["offer","rejected","withdrawn"]);
const allowed:Record<TargetJobStatus,TargetJobStatus[]>={considering:["preparing","withdrawn"],preparing:["applied","withdrawn"],applied:["interviewing","withdrawn"],interviewing:["offer","rejected","withdrawn"],offer:[],rejected:[],withdrawn:[]};

export class TargetService {
  constructor(private readonly ws:FileWorkspace){}
  async createCareerTarget(name:string,description?:string,activate=true):Promise<CareerTarget>{const list=await this.ws.getCareerTargets();const t:CareerTarget={schemaVersion:1,id:newId("career"),name,description,createdAt:nowIso()};list.push(t);await this.ws.saveCareerTargets(list);if(activate){const a=await this.ws.getActiveTargets();await this.ws.saveActiveTargets({...a,activeCareerTargetId:t.id,activeTargetJobId:undefined,updatedAt:nowIso()});}return t;}
  async createTargetJob(input:{careerTargetId:string;title:string;company?:string;jdText:string;interviewDate?:string;deadline?:string},activate=true):Promise<TargetJob>{const careers=await this.ws.getCareerTargets();if(!careers.some(c=>c.id===input.careerTargetId))throw new Error("Unknown career target");const jobs=await this.ws.getTargetJobs();const now=nowIso();const j:TargetJob={schemaVersion:1,id:newId("job"),careerTargetId:input.careerTargetId,title:input.title,company:input.company,jdText:input.jdText,status:"preparing",interviewDate:input.interviewDate,deadline:input.deadline,createdAt:now,updatedAt:now};jobs.push(j);await this.ws.saveTargetJobs(jobs);if(activate){const a=await this.ws.getActiveTargets();await this.ws.saveActiveTargets({...a,activeCareerTargetId:input.careerTargetId,activeTargetJobId:j.id,updatedAt:nowIso()});}return j;}
  async activateCareer(id:string):Promise<void>{const list=await this.ws.getCareerTargets();if(!list.some(x=>x.id===id&&!x.archived))throw new Error("Unknown career target");const a=await this.ws.getActiveTargets();await this.ws.saveActiveTargets({...a,activeCareerTargetId:id,activeTargetJobId:undefined,updatedAt:nowIso()});}
  async activateJob(id:string):Promise<void>{const jobs=await this.ws.getTargetJobs();const j=jobs.find(x=>x.id===id);if(!j)throw new Error("Unknown target job");if(terminal.has(j.status))throw new Error("Cannot activate terminal target job");const a=await this.ws.getActiveTargets();await this.ws.saveActiveTargets({...a,activeCareerTargetId:j.careerTargetId,activeTargetJobId:j.id,updatedAt:nowIso()});}
  async transitionJob(id:string,status:TargetJobStatus):Promise<TargetJob>{const jobs=await this.ws.getTargetJobs();const i=jobs.findIndex(x=>x.id===id);if(i<0)throw new Error("Unknown target job");const current=jobs[i]!;if(current.status!==status&&!allowed[current.status].includes(status))throw new Error(`Illegal target job transition ${current.status} -> ${status}`);const updated={...current,status,updatedAt:nowIso()};jobs[i]=updated;await this.ws.saveTargetJobs(jobs);if(terminal.has(status)){const a=await this.ws.getActiveTargets();if(a.activeTargetJobId===id)await this.ws.saveActiveTargets({...a,activeTargetJobId:undefined,updatedAt:nowIso()});}return updated;}
  async active():Promise<{active:ActiveTargets;career?:CareerTarget;job?:TargetJob}>{const active=await this.ws.getActiveTargets();const career=(await this.ws.getCareerTargets()).find(x=>x.id===active.activeCareerTargetId);const job=(await this.ws.getTargetJobs()).find(x=>x.id===active.activeTargetJobId);return{active,career,job};}
}
