import test from "node:test";
import assert from "node:assert/strict";
import { createApp } from "../src/app.js";
import { tempWorkspace, recorded } from "./helpers.js";
import { newId, nowIso } from "../src/shared/utils.js";
import type { TaskSession } from "../src/domain/types.js";

async function baseApp(){const root=await tempWorkspace(),llm=await recorded();const app=await createApp({workspaceRoot:root,userId:"u",projectRoot:process.cwd(),llm});await app.targets.createCareerTarget("Backend Engineer");return app;}

test("assessment evaluator writes competency observation from recorded real model output",async()=>{const app=await baseApp();const id=newId("task");const task:TaskSession={schemaVersion:1,id,type:"assessment",status:"completed",createdAt:nowIso(),updatedAt:nowIso(),input:{competencyId:"java.concurrency"},localState:{coveredAreas:["JMM"],probeCount:3,measurementStatus:"clean"},transcriptPath:`tasks/${id}/transcript.jsonl`,contextSnapshotPath:`tasks/${id}/context.json`,contextBinding:{}};await app.ws.createTask(task,{competency:{id:"java.concurrency"}});for(const [role,content] of [["assistant","Explain happens-before."],["user","A volatile write happens-before a later volatile read of the same variable; locks and thread start/join also establish ordering."],["assistant","What if a bounded pool saturates?"],["user","I would choose a rejection/backpressure strategy based on caller semantics rather than silently growing an unbounded queue."]] as const)await app.ws.appendTranscript({schemaVersion:1,id:newId("msg"),ts:nowIso(),role,content,taskId:id});await app.taskEvaluation.evaluate(id);const s=(await app.ws.getUserModel()).competencies["java.concurrency"]!;assert.ok((s.mastery??0)>0.7);assert.equal(s.status,"current");});

test("tutor evidence updates competency but never creates project evidence",async()=>{const app=await baseApp();const id=newId("task");const task:TaskSession={schemaVersion:1,id,type:"tutor",status:"completed",createdAt:nowIso(),updatedAt:nowIso(),input:{competencyIds:["mysql.mvcc"]},localState:{objectives:["mysql.mvcc"],coveredTopics:["Read View"]},transcriptPath:`tasks/${id}/transcript.jsonl`,contextSnapshotPath:`tasks/${id}/context.json`,contextBinding:{}};await app.ws.createTask(task,{});await app.ws.appendTranscript({schemaVersion:1,id:newId("msg"),ts:nowIso(),role:"user",content:"Under RC each consistent read gets a new Read View; under RR the transaction generally reuses the first consistent-read view.",taskId:id});const before=(await app.ws.getEvidence()).length;const result:any=await app.taskEvaluation.evaluate(id);assert.equal((await app.ws.getEvidence()).length,before);assert.ok((await app.ws.getUserModel()).competencies["mysql.mvcc"]);assert.ok(result.learningArtifact);});

test("interview can keep competency strong while recording weak delivery",async()=>{const app=await baseApp();const id=newId("task");const task:TaskSession={schemaVersion:1,id,type:"interview",status:"completed",createdAt:nowIso(),updatedAt:nowIso(),input:{mode:"full_mock"},localState:{coveredTopics:["java"],mode:"full_mock",feedbackRequested:false,measurementStatus:"clean"},transcriptPath:`tasks/${id}/transcript.jsonl`,contextSnapshotPath:`tasks/${id}/context.json`,contextBinding:{}};await app.ws.createTask(task,{claims:[]});await app.ws.appendTranscript({schemaVersion:1,id:newId("msg"),ts:nowIso(),role:"user",content:"Technically the visibility guarantee comes from happens-before... [long meandering explanation]",taskId:id});await app.taskEvaluation.evaluate(id);const model=await app.ws.getUserModel();assert.ok((model.competencies["java.concurrency"]?.mastery??0)>0.7);assert.ok((model.interview.clarity?.value??1)<0.5);});
