import test from "node:test";
import assert from "node:assert/strict";
import { createApp } from "../src/app.js";
import { FileWorkspace } from "../src/infrastructure/filesystem/file-workspace.js";
import { RecordedStructuredLLM } from "../src/infrastructure/llm/recorded-structured-llm.js";
import { tempWorkspace, recorded, sampleResume, sampleJd, writeTempFile } from "./helpers.js";
import { newId, nowIso } from "../src/shared/utils.js";
import type { ResumeClaim, TaskSession } from "../src/domain/types.js";

async function boot(){const root=await tempWorkspace(),llm=await recorded();const app=await createApp({workspaceRoot:root,userId:"u",projectRoot:process.cwd(),llm});const r=await app.bootstrap.run({userId:"u",careerTarget:"Backend Engineer",resumeText:sampleResume,targetJob:{title:"Backend Engineer",company:"Example",jdText:sampleJd}});return{root,app,jobId:r.activeTargetJobId!};}

test("GJ: terminal target deactivates without automatically switching another target",async()=>{const {app,jobId}=await boot();await app.targets.transitionJob(jobId,"applied");await app.targets.transitionJob(jobId,"interviewing");await app.targets.transitionJob(jobId,"rejected");assert.equal((await app.ws.getActiveTargets()).activeTargetJobId,undefined);});

test("GJ: rejection alone is outcome history, not competency evidence",async()=>{const {app,jobId}=await boot();await app.targets.transitionJob(jobId,"applied");await app.targets.transitionJob(jobId,"interviewing");const before=(await app.ws.getObservations()).length;await app.outcomes.record({targetJobId:jobId,kind:"rejection"});assert.equal((await app.ws.getObservations()).length,before);assert.equal((await app.ws.getTargetJobs()).find(j=>j.id===jobId)?.status,"rejected");});

test("GJ: concrete real feedback may become attributable observation",async()=>{const {app,jobId}=await boot();const before=(await app.ws.getObservations()).length;await app.outcomes.record({targetJobId:jobId,kind:"feedback",feedback:"The interviewer said my system design did not explain scaling bottlenecks or failure isolation deeply enough."});assert.equal((await app.ws.getObservations()).length,before+1);assert.ok((await app.ws.getUserModel()).competencies["system-design.scalability"]);});

test("GJ: paused measurement cannot resume after target switch",async()=>{const {app}=await boot();const oldActive=await app.ws.getActiveTargets();const id=newId("task");const task:TaskSession={schemaVersion:1,id,type:"assessment",status:"paused",createdAt:nowIso(),updatedAt:nowIso(),input:{competencyId:"java.concurrency",targetJobId:oldActive.activeTargetJobId},localState:{coveredAreas:[],probeCount:1,measurementStatus:"clean"},transcriptPath:`tasks/${id}/transcript.jsonl`,contextSnapshotPath:`tasks/${id}/context.json`,contextBinding:{careerTargetId:oldActive.activeCareerTargetId,targetJobId:oldActive.activeTargetJobId}};await app.ws.createTask(task,{});const career=(await app.ws.getCareerTargets())[0]!;const j2=await app.targets.createTargetJob({careerTargetId:career.id,title:"Another Backend",jdText:"Backend role"},true);await assert.rejects(()=>app.tasks.resume(id),/active target changed/);});

test("GJ: user fact correction differs from evaluation challenge",async()=>{const {app}=await boot();const obs=(await app.ws.getObservations())[0]!;const before=await app.ws.readText("profile.md");await app.userModel.correctProfileFact("Project date is 2023, not 2024.");assert.ok((await app.ws.readText("profile.md")).length>before.length);await app.userModel.contestObservation(obs.id,"This assessment reflected an interruption, not my actual level.");assert.equal((await app.ws.getObservations()).some(o=>o.id===obs.id),true);assert.equal((await app.ws.getActiveObservations()).some(o=>o.id===obs.id),false);});

test("GJ: claim-level evidence does not inherit entity-level supported status",async()=>{const root=await tempWorkspace();const entry:any={name:"evidence.analyze",model:"GPT-5.6 Sol",provenance:"Current implementation session",capturedAt:nowIso(),output:{evidence:[{title:"Redis README",type:"document",description:"Documents cache-aside implementation",confidence:"supported",competencyIds:["redis.cache-consistency"]}],claimSupport:[{claimId:"claim_metric",level:"partial",rationale:"Redis use is supported, but the 40% latency metric has no benchmark evidence.",evidenceIndexes:[0]}]}};const llm=new RecordedStructuredLLM([entry]);const app=await createApp({workspaceRoot:root,userId:"u",projectRoot:process.cwd(),llm});await app.targets.createCareerTarget("Backend");const claim:ResumeClaim={schemaVersion:1,id:"claim_metric",text:"Improved latency by 40% using Redis",competencyIds:["redis.cache-consistency"],createdAt:nowIso()};await app.ws.saveResumeClaims([claim]);const p=await writeTempFile(root,"README-evidence.md","We implemented Redis cache-aside and delete cache after database updates. No benchmark numbers are documented.");const r=await app.evidence.analyze([p]);assert.equal(r.evidence[0]?.confidence,"supported");assert.equal(r.claimSupport[0]?.level,"partial");});

test("GJ: one active interactive task invariant is enforced before Pi is invoked",async()=>{const root=await tempWorkspace(),llm=await recorded();const app=await createApp({workspaceRoot:root,userId:"u",projectRoot:process.cwd(),llm});const wf=await app.ws.getWorkflow();await app.ws.saveWorkflow({...wf,activeTaskId:"already-active",updatedAt:nowIso()});await assert.rejects(()=>app.tasks.start("assessment",{competencyId:"java.concurrency"},{}),/already active/);});
