import { FileWorkspace } from "../infrastructure/filesystem/file-workspace.js";
import type { StructuredLLM } from "../infrastructure/llm/structured-llm.js";
import { StateUpdater } from "../application/state-update/state-updater.js";
import { nowIso } from "../shared/utils.js";
const SYSTEM=`Compact longitudinal career state into a concise user-facing profile summary. Preserve important stable strengths, repeated weaknesses, misconceptions, interview patterns, preferences and material changes. Do not invent facts and do not replace raw observations. Return JSON {markdown}.`;
export class MaintenanceService{
  constructor(private readonly ws:FileWorkspace,private readonly llm:StructuredLLM,private readonly updater:StateUpdater){}
  async compactProfile():Promise<{path:string}>{const model=await this.ws.getUserModel(),recent=(await this.ws.getActiveObservations()).slice(-40),experience=(await this.ws.getCareerExperience()).slice(-20);const res=await this.llm.complete<any>({name:"memory.compact",system:SYSTEM,input:{model,recentObservations:recent,careerExperience:experience},promptVersion:"memory-compact-v1"});const path="summaries/career-state.md";await this.ws.writeText(path,String(res.output.markdown||""));return{path};}
  async validateWorkspace():Promise<{ok:boolean;errors:string[];warnings:string[]}>{const errors:string[]=[],warnings:string[]=[];try{await this.ws.getUserModel();}catch(e){errors.push(`User model: ${(e as Error).message}`);}try{await this.ws.getObservations();await this.ws.getAmendments();}catch(e){errors.push(`Observation log: ${(e as Error).message}`);}const active=await this.ws.getActiveTargets(),jobs=await this.ws.getTargetJobs(),careers=await this.ws.getCareerTargets();if(active.activeCareerTargetId&&!careers.some(c=>c.id===active.activeCareerTargetId))errors.push("activeCareerTargetId is dangling");if(active.activeTargetJobId&&!jobs.some(j=>j.id===active.activeTargetJobId))errors.push("activeTargetJobId is dangling");const wf=await this.ws.getWorkflow();if(wf.activeTaskId){const t=await this.ws.getTask(wf.activeTaskId);if(!t||t.status!=="active")errors.push("workflow activeTaskId is inconsistent");}const supports=await this.ws.getClaimSupport(),claims=await this.ws.getResumeClaims();for(const s of supports)if(!claims.some(c=>c.id===s.claimId))warnings.push(`ClaimSupport ${s.claimId} is dangling`);return{ok:errors.length===0,errors,warnings};}
  async rebuildDerivedState():Promise<void>{await this.updater.rebuild();}
  async exportSummary():Promise<string>{const a=await this.ws.getActiveTargets(),model=await this.ws.getUserModel();return JSON.stringify({exportedAt:nowIso(),activeTargets:a,userModel:model,evidence:await this.ws.getEvidence(),claimSupport:await this.ws.getClaimSupport()},null,2);}
}
