import type { ClaimSupport, Evidence } from "../domain/types.js";
import { CompetencyCatalog } from "../competency/catalog.js";
import { FileWorkspace } from "../infrastructure/filesystem/file-workspace.js";
import { SourceIngestor } from "../infrastructure/filesystem/source-ingestor.js";
import type { StructuredLLM } from "../infrastructure/llm/structured-llm.js";
import { newId, nowIso } from "../shared/utils.js";

const SYSTEM=`Analyze existing user material as career evidence. Never invent work, ownership, metrics, technologies or results. Determine evidence entity confidence (claimed/confirmed/supported) from the supplied material itself and evaluate each existing resume claim separately. A document supporting "used Redis" does not support "latency improved 40%" unless the metric is actually evidenced. Return JSON {evidence:[{title,type,description,confidence,competencyIds}],claimSupport:[{claimId,level,rationale,evidenceIndexes:[number]}]}. Use only allowed competency and claim IDs.`;
export class EvidenceService {
  constructor(private readonly ws:FileWorkspace,private readonly llm:StructuredLLM,private readonly catalog:CompetencyCatalog,private readonly ingestor=new SourceIngestor()){}
  async analyze(paths:string[]):Promise<{evidence:Evidence[];claimSupport:ClaimSupport[]}>{const materials=[] as any[];for(const p of paths){materials.push({path:p,text:await this.ingestor.toText(p)});}const claims=await this.ws.getResumeClaims();const ids=this.catalog.assessable().map(n=>n.id);const res=await this.llm.complete<any>({name:"evidence.analyze",system:SYSTEM,input:{materials,claims},promptVersion:"evidence-v1",allowedValues:{competencyId:ids,claimId:claims.map(c=>c.id)}});const existing=await this.ws.getEvidence();const created:Evidence[]=[];for(const e of res.output.evidence??[]){const ev:Evidence={schemaVersion:1,id:newId("evidence"),title:String(e.title),type:["project","work_experience","code","document","benchmark","other"].includes(e.type)?e.type:"other",description:String(e.description),confidence:["claimed","confirmed","supported"].includes(e.confidence)?e.confidence:"claimed",competencyIds:(e.competencyIds??[]).filter((id:string)=>this.catalog.has(id)),artifactRefs:[],sourceRefs:materials.map(m=>({id:newId("src"),kind:"file" as const,locator:m.path,capturedAt:nowIso()})),createdAt:nowIso(),updatedAt:nowIso()};created.push(ev);}const supports:ClaimSupport[]=(res.output.claimSupport??[]).filter((x:any)=>claims.some(c=>c.id===x.claimId)).map((x:any)=>({schemaVersion:1,claimId:x.claimId,evidenceIds:(x.evidenceIndexes??[]).map((i:number)=>created[i]?.id).filter(Boolean),level:["unsupported","partial","supported","self_report_only"].includes(x.level)?x.level:"unsupported",rationale:String(x.rationale),evaluatedAt:nowIso(),evaluator:{model:res.model,promptVersion:"evidence-v1"}}));await this.ws.saveEvidence([...existing,...created]);const map=new Map((await this.ws.getClaimSupport()).map(x=>[x.claimId,x]));for(const s of supports)map.set(s.claimId,s);await this.ws.saveClaimSupport([...map.values()]);return{evidence:created,claimSupport:supports};}
}
