import type { RoleCompetencyProfile } from "../../domain/types.js";
import { CompetencyCatalog } from "../../competency/catalog.js";
import { FileWorkspace } from "../../infrastructure/filesystem/file-workspace.js";
import type { StructuredLLM } from "../../infrastructure/llm/structured-llm.js";
import { newId, nowIso } from "../../shared/utils.js";
const SYSTEM=`Map the active career target or target job into canonical competency requirements. Authority order: explicit JD > canonical role expectation > current market evidence > LLM inference. Market evidence supplements but never overrides an explicit concrete JD. Personal career experience is user-specific, never global truth. Return JSON {requirements:[{competencyId,importance,requiredMastery,authority,sourceText,rationale}]}. Use only allowed competency IDs.`;
export class RoleAnalysisService{
  constructor(private readonly ws:FileWorkspace,private readonly llm:StructuredLLM,private readonly catalog:CompetencyCatalog){}
  async analyze(marketEvidence?:string):Promise<RoleCompetencyProfile>{const active=await this.ws.getActiveTargets();const jobs=await this.ws.getTargetJobs(),careers=await this.ws.getCareerTargets();const job=jobs.find(x=>x.id===active.activeTargetJobId),career=careers.find(x=>x.id===(job?.careerTargetId??active.activeCareerTargetId));if(!career)throw new Error("No active career target");const text=job?`${job.company??""} ${job.title}\n${job.jdText}`:`${career.name}\n${career.description??""}`;const retrieved=this.catalog.retrieve(text,24);const candidates=(retrieved.length?retrieved.map(x=>x.node):this.catalog.assessable()).map(n=>({id:n.id,name:n.name,description:n.description,domain:n.domain}));const res=await this.llm.complete<any>({name:"role.analyze",system:SYSTEM,input:{career,job,marketEvidence,canonicalCandidates:candidates},promptVersion:"role-v1",allowedValues:{competencyId:candidates.map(c=>c.id)}});const reqs=(res.output.requirements??[]).filter((r:any)=>this.catalog.has(r.competencyId)).map((r:any)=>({competencyId:r.competencyId,importance:Math.max(0,Math.min(1,Number(r.importance))),requiredMastery:Math.max(0,Math.min(1,Number(r.requiredMastery))),authority:["jd_explicit","canonical","market","llm_inferred","personal_experience"].includes(r.authority)?r.authority:"llm_inferred",sourceText:r.sourceText,rationale:r.rationale}));const profile:RoleCompetencyProfile={schemaVersion:1,id:newId("role"),scope:job?"target_job":"career",scopeId:job?.id??career.id,catalogVersion:this.catalog.version,generatedAt:nowIso(),requirements:reqs};await this.ws.saveRoleProfile(profile);return profile;}
}
