import type { Evidence, Observation, ResumeClaim, RoleCompetencyProfile } from "../../domain/types.js";
import { CompetencyCatalog } from "../../competency/catalog.js";
import { FileWorkspace } from "../../infrastructure/filesystem/file-workspace.js";
import { SourceIngestor } from "../../infrastructure/filesystem/source-ingestor.js";
import type { StructuredLLM } from "../../infrastructure/llm/structured-llm.js";
import { TargetService } from "../../targets/target-service.js";
import { StateUpdater } from "../state-update/state-updater.js";
import { newId, nowIso, uniq } from "../../shared/utils.js";

interface ParsedResume { profileSummary:string; claims:Array<{text:string;section?:string;competencyHints?:string[]}>; evidenceCandidates:Array<{title:string;type:Evidence["type"];description:string;competencyHints?:string[]}> }
interface RoleMap { requirements:Array<{competencyId:string;importance:number;requiredMastery:number;authority:"jd_explicit"|"canonical"|"market"|"llm_inferred";sourceText?:string;rationale?:string}> }
interface ResumeCompEval { observations:Array<{competencyId:string;masterySignal:number;evidenceStrength:number;confidence:number;summary:string}> }

const RESUME_PARSE=`Parse the resume into a concise profile summary, factual claims, and candidate evidence statements. Do not infer achievements not stated. Return JSON {profileSummary,claims:[{text,section,competencyHints}],evidenceCandidates:[{title,type,description,competencyHints}]}. type is project,work_experience,code,document,benchmark,other.`;
const ROLE_MAP=`Map the career target or concrete JD to canonical competency IDs supplied in candidates. Explicit JD requirements have highest authority. Canonical expectations may supplement; do not invent unsupported exotic requirements. Return JSON {requirements:[{competencyId,importance,requiredMastery,authority,sourceText,rationale}]}. Use only allowed competency IDs.`;
const RESUME_COMP=`Evaluate only what the resume weakly suggests about the user's competency. Resume claims are low-strength evidence; never give high confidence merely because the resume says "expert". Return JSON {observations:[{competencyId,masterySignal,evidenceStrength,confidence,summary}]}. Use only allowed competency IDs.`;

export interface BootstrapInput { userId:string; careerTarget:string; careerDescription?:string; resumePath?:string; resumeText?:string; targetJob?:{title:string;company?:string;jdPath?:string;jdText?:string;interviewDate?:string;deadline?:string} }
export interface BootstrapResult { careerTargetId:string; activeTargetJobId?:string; roleProfileId:string; initialObservations:number; evidenceCandidates:number; resumeClaims:number }

export class BootstrapWorkflow {
  constructor(private readonly ws:FileWorkspace,private readonly llm:StructuredLLM,private readonly catalog:CompetencyCatalog,private readonly updater:StateUpdater,private readonly ingestor=new SourceIngestor()){}
  async run(input:BootstrapInput):Promise<BootstrapResult>{await this.ws.init();const trace=newId("trace");await this.ws.runtimeEvent("bootstrap.started",trace,{careerTarget:input.careerTarget});
    const resumeText=input.resumeText??(input.resumePath?await this.ingestor.toText(input.resumePath):""); if(!resumeText.trim())throw new Error("Bootstrap requires resumePath or resumeText"); if(input.resumePath)await this.ws.saveSourceCopy(input.resumePath,"resume"); await this.ws.writeText("sources/resume/normalized.md",resumeText);
    const parsed=(await this.llm.complete<ParsedResume>({name:"bootstrap.resume_parse",system:RESUME_PARSE,input:{resume:resumeText},promptVersion:"resume-parse-v1"})).output;
    await this.ws.writeText("profile.md",`# Career Profile\n\n${parsed.profileSummary||""}\n`);
    const targets=new TargetService(this.ws);const career=await targets.createCareerTarget(input.careerTarget,input.careerDescription,true);let jobId:string|undefined;let roleText=`Career Target: ${input.careerTarget}\n${input.careerDescription??""}`;
    if(input.targetJob){const jd=input.targetJob.jdText??(input.targetJob.jdPath?await this.ingestor.toText(input.targetJob.jdPath):""); if(!jd.trim())throw new Error("Target job requires JD text/path");const job=await targets.createTargetJob({careerTargetId:career.id,title:input.targetJob.title,company:input.targetJob.company,jdText:jd,interviewDate:input.targetJob.interviewDate,deadline:input.targetJob.deadline},true);jobId=job.id;roleText=`${input.targetJob.company??""} ${input.targetJob.title}\n${jd}`;}
    const retrieved=this.catalog.retrieve(roleText,Math.min(24,this.catalog.assessable().length));const candidates=(retrieved.length?retrieved.map(x=>x.node):this.catalog.assessable()).map(n=>({id:n.id,name:n.name,description:n.description,domain:n.domain}));const roleRes=await this.llm.complete<RoleMap>({name:"bootstrap.role_map",system:ROLE_MAP,input:{careerTarget:input.careerTarget,targetJob:input.targetJob,canonicalCandidates:candidates},promptVersion:"role-map-v1",allowedValues:{competencyId:candidates.map(c=>c.id)}});const reqs=(roleRes.output.requirements??[]).filter(r=>this.catalog.has(r.competencyId)).map(r=>({...r,importance:Math.max(0,Math.min(1,r.importance)),requiredMastery:Math.max(0,Math.min(1,r.requiredMastery))}));const profile:RoleCompetencyProfile={schemaVersion:1,id:newId("role"),scope:jobId?"target_job":"career",scopeId:jobId??career.id,catalogVersion:this.catalog.version,generatedAt:nowIso(),requirements:reqs};await this.ws.saveRoleProfile(profile);
    const claims:ResumeClaim[]=(parsed.claims??[]).map(c=>({schemaVersion:1,id:newId("claim"),text:c.text,section:c.section,competencyIds:[],createdAt:nowIso()}));const allowed=uniq(reqs.map(r=>r.competencyId));const compRes=await this.llm.complete<ResumeCompEval>({name:"bootstrap.resume_competencies",system:RESUME_COMP,input:{resume:resumeText,roleCompetencies:allowed},promptVersion:"resume-comp-v1",allowedValues:{competencyId:allowed}});const evalId=newId("eval");const observations:Observation[]=(compRes.output.observations??[]).filter(o=>allowed.includes(o.competencyId)).map(o=>({schemaVersion:1,id:newId("obs"),evaluationId:evalId,semanticKey:`competency:${o.competencyId}`,timestamp:nowIso(),source:"resume",target:{type:"competency",competencyId:o.competencyId},masterySignal:o.masterySignal,evidenceStrength:o.evidenceStrength,confidence:o.confidence,summary:o.summary,evaluator:{name:"resume-competency-evaluator",model:compRes.model,promptVersion:"resume-comp-v1"}}));
    const evidence:Evidence[]=(parsed.evidenceCandidates??[]).map(e=>({schemaVersion:1,id:newId("evidence"),title:e.title,type:e.type,description:e.description,confidence:"claimed",competencyIds:[],artifactRefs:[],sourceRefs:[{id:newId("src"),kind:"file",locator:"sources/resume/normalized.md",capturedAt:nowIso()}],createdAt:nowIso(),updatedAt:nowIso()}));await this.ws.saveResumeClaims(claims);await this.ws.saveEvidence(evidence);await this.updater.apply(observations,trace);
    await this.ws.writeText("resumes/master.md",resumeText);await this.ws.writeText("resumes/master.version",newId("resumev"));if(jobId){await this.ws.writeText(`resumes/targets/${jobId}.md`,resumeText);await this.ws.writeText(`resumes/targets/${jobId}.version`,newId("resumev"));}
    await this.ws.runtimeEvent("bootstrap.completed",trace,{careerTargetId:career.id,targetJobId:jobId,roleRequirements:reqs.length,observations:observations.length});return{careerTargetId:career.id,activeTargetJobId:jobId,roleProfileId:profile.id,initialObservations:observations.length,evidenceCandidates:evidence.length,resumeClaims:claims.length};}
}
