import type { ClaimSupport, Observation, TaskSession, TranscriptMessage } from "../domain/types.js";
import type { StructuredLLM } from "../infrastructure/llm/structured-llm.js";
import type { CompetencyCatalog } from "../competency/catalog.js";
import { newId, nowIso } from "../shared/utils.js";

function transcriptText(messages:TranscriptMessage[]):string{return messages.map(m=>`${m.role.toUpperCase()}: ${m.content}`).join("\n\n")}
function obsBase(input:{evaluationId:string;source:Observation["source"];taskId?:string;summary:string;strength:number;confidence:number;model?:string;promptVersion:string}):Omit<Observation,"target"|"semanticKey">{return{schemaVersion:1,id:newId("obs"),evaluationId:input.evaluationId,timestamp:nowIso(),source:input.source,evidenceStrength:input.strength,confidence:input.confidence,taskId:input.taskId,summary:input.summary,evaluator:{name:`${input.source}-evaluator`,model:input.model,promptVersion:input.promptVersion}}}

export interface AssessmentEvaluation { contaminated:boolean; useful:boolean; competencyId:string; masterySignal:number; evidenceStrength:number; confidence:number; strengths:string[]; weaknesses:string[]; misconceptions:string[]; rationale:string }
export interface TutorEvaluation { observations:Array<{competencyId:string;masterySignal:number;evidenceStrength:number;confidence:number;strengths?:string[];weaknesses?:string[];misconceptions?:string[];summary:string}>; learningSummary:string; reviewQuestions?:string[] }
export interface InterviewEvaluation { contaminated:boolean; competencyObservations:Array<{competencyId:string;masterySignal:number;evidenceStrength:number;confidence:number;summary:string;strengths?:string[];weaknesses?:string[];misconceptions?:string[]}>; interviewObservations:Array<{dimension:string;signal:number;evidenceStrength:number;confidence:number;summary:string}>; claimFindings:Array<{claimId:string;level:"unsupported"|"partial"|"supported"|"self_report_only";rationale:string}>; overallFeedback:string }

const ASSESS_SYSTEM=`Independently evaluate an assessment transcript. You are not the AssessmentAgent. Determine whether the measurement was contaminated by teaching, correct-answer disclosure, or evaluative feedback before measurement ended. If contaminated, contaminated=true and do not treat post-contamination performance as valid evidence. Evaluate only the target competency. Return JSON {contaminated,useful,competencyId,masterySignal,evidenceStrength,confidence,strengths,weaknesses,misconceptions,rationale}. evidenceStrength means how much this exact interaction tells us about capability; simple/trivial questions should be weak even when correct.`;
const TUTOR_SYSTEM=`Independently evaluate a tutoring transcript for demonstrated learner performance. Do not treat the tutor's explanations or the user's mere "I understand" as evidence. Emit observations only for competencies where the user actually reasoned, explained, solved, compared, debugged, or otherwise demonstrated capability. Return JSON {observations:[{competencyId,masterySignal,evidenceStrength,confidence,strengths,weaknesses,misconceptions,summary}],learningSummary,reviewQuestions}.`;
const INTERVIEW_SYSTEM=`Independently evaluate a mock interview transcript. Detect contamination: if the interviewer taught, disclosed answers, or gave evaluative feedback before the measurement ended, contaminated=true and exclude contaminated evidence. Separate competency knowledge from interview performance. Return JSON {contaminated,competencyObservations:[...],interviewObservations:[{dimension,signal,evidenceStrength,confidence,summary}],claimFindings:[{claimId,level,rationale}],overallFeedback}. Valid interview dimensions: technical_accuracy,depth,clarity,structure,follow_up_stability.`;

export class TaskEvaluators {
  constructor(private readonly llm:StructuredLLM,private readonly catalog:CompetencyCatalog){}
  async assessment(task:TaskSession,messages:TranscriptMessage[],context:unknown):Promise<{observations:Observation[];evaluation:AssessmentEvaluation}>{
    const comp=(task.input as any).competencyId as string; const res=await this.llm.complete<AssessmentEvaluation>({name:"assessment.evaluate",system:ASSESS_SYSTEM,input:{targetCompetencyId:comp,context,transcript:transcriptText(messages)},promptVersion:"assessment-eval-v1",allowedValues:{competencyId:[comp]}}); const e=res.output; const evaluationId=newId("eval");
    if(e.contaminated||!e.useful||!this.catalog.has(comp))return{observations:[],evaluation:e};
    const base=obsBase({evaluationId,source:"assessment",taskId:task.id,summary:e.rationale,strength:e.evidenceStrength,confidence:e.confidence,model:res.model,promptVersion:"assessment-eval-v1"});return{observations:[{...base,semanticKey:`competency:${comp}`,target:{type:"competency",competencyId:comp},masterySignal:e.masterySignal,strengths:e.strengths,weaknesses:e.weaknesses,misconceptions:e.misconceptions,evidenceRefs:messages.filter(m=>m.role==="user").map(m=>m.id)}],evaluation:e};
  }
  async tutor(task:TaskSession,messages:TranscriptMessage[],context:unknown):Promise<{observations:Observation[];evaluation:TutorEvaluation}>{const allowed=(task.input as any).competencyIds as string[];const res=await this.llm.complete<TutorEvaluation>({name:"tutor.evaluate",system:TUTOR_SYSTEM,input:{targetCompetencyIds:allowed,context,transcript:transcriptText(messages)},promptVersion:"tutor-eval-v1",allowedValues:{competencyId:this.catalog.validateIds([...allowed,...this.catalog.assessable().map(n=>n.id)])}});const evaluationId=newId("eval");const observations:Observation[]=[];for(const e of res.output.observations??[]){if(!this.catalog.has(e.competencyId))continue;const base=obsBase({evaluationId,source:"tutor",taskId:task.id,summary:e.summary,strength:e.evidenceStrength,confidence:e.confidence,model:res.model,promptVersion:"tutor-eval-v1"});observations.push({...base,semanticKey:`competency:${e.competencyId}`,target:{type:"competency",competencyId:e.competencyId},masterySignal:e.masterySignal,strengths:e.strengths,weaknesses:e.weaknesses,misconceptions:e.misconceptions,evidenceRefs:messages.filter(m=>m.role==="user").map(m=>m.id)});}return{observations,evaluation:res.output};}
  async interview(task:TaskSession,messages:TranscriptMessage[],context:any):Promise<{observations:Observation[];evaluation:InterviewEvaluation;claimSupport:ClaimSupport[]}>{const allowedComp=this.catalog.assessable().map(n=>n.id);const allowedClaims=(context.claims??[]).map((c:any)=>c.id);const res=await this.llm.complete<InterviewEvaluation>({name:"interview.evaluate",system:INTERVIEW_SYSTEM,input:{context,transcript:transcriptText(messages)},promptVersion:"interview-eval-v1",allowedValues:{competencyId:allowedComp,dimension:["technical_accuracy","depth","clarity","structure","follow_up_stability"],claimId:allowedClaims}});const evalId=newId("eval");const observations:Observation[]=[];if(!res.output.contaminated){for(const e of res.output.competencyObservations??[]){if(!this.catalog.has(e.competencyId))continue;const b=obsBase({evaluationId:evalId,source:"interview",taskId:task.id,summary:e.summary,strength:e.evidenceStrength,confidence:e.confidence,model:res.model,promptVersion:"interview-eval-v1"});observations.push({...b,semanticKey:`competency:${e.competencyId}`,target:{type:"competency",competencyId:e.competencyId},masterySignal:e.masterySignal,strengths:e.strengths,weaknesses:e.weaknesses,misconceptions:e.misconceptions});}for(const e of res.output.interviewObservations??[]){if(!["technical_accuracy","depth","clarity","structure","follow_up_stability"].includes(e.dimension))continue;const b=obsBase({evaluationId:evalId,source:"interview",taskId:task.id,summary:e.summary,strength:e.evidenceStrength,confidence:e.confidence,model:res.model,promptVersion:"interview-eval-v1"});observations.push({...b,semanticKey:`interview:${e.dimension}`,target:{type:"interview_dimension",dimension:e.dimension as any},signal:e.signal});}}
    const claimSupport=(res.output.claimFindings??[]).filter(x=>allowedClaims.includes(x.claimId)).map(x=>({schemaVersion:1 as const,claimId:x.claimId,evidenceIds:[],level:x.level,rationale:x.rationale,evaluatedAt:nowIso(),evaluator:{model:res.model,promptVersion:"interview-eval-v1"}}));return{observations,evaluation:res.output,claimSupport};}
}
