import type { CareerExperienceEvent, Observation } from "../domain/types.js";
import { CompetencyCatalog } from "../competency/catalog.js";
import { FileWorkspace } from "../infrastructure/filesystem/file-workspace.js";
import type { StructuredLLM } from "../infrastructure/llm/structured-llm.js";
import { StateUpdater } from "../application/state-update/state-updater.js";
import { TargetService } from "../targets/target-service.js";
import { newId, nowIso } from "../shared/utils.js";
const SYSTEM=`Analyze concrete real-world interview/application feedback. The outcome label (offer/rejection) by itself is NOT competency evidence. Only turn specific attributable feedback into observations. Return JSON {observations:[{targetType:"competency"|"interview_dimension",competencyId?,dimension?,signal,masterySignal?,evidenceStrength,confidence,summary}],experienceSummary}. Use only allowed canonical competency IDs and interview dimensions.`;
export class OutcomeService {
  constructor(private readonly ws:FileWorkspace,private readonly llm:StructuredLLM,private readonly catalog:CompetencyCatalog,private readonly updater:StateUpdater){}
  async record(input:{targetJobId:string;kind:"application"|"real_interview"|"offer"|"rejection"|"withdrawn"|"feedback";feedback?:string}):Promise<{observations:number}>{const event:CareerExperienceEvent={schemaVersion:1,id:newId("career_event"),targetJobId:input.targetJobId,kind:input.kind,summary:input.feedback||input.kind,timestamp:nowIso()};await this.ws.appendCareerExperience(event);let observations:Observation[]=[];if(input.feedback?.trim()){const ids=this.catalog.assessable().map(n=>n.id);const res=await this.llm.complete<any>({name:"outcome.analyze",system:SYSTEM,input:{kind:input.kind,feedback:input.feedback},promptVersion:"outcome-v1",allowedValues:{competencyId:ids,dimension:["technical_accuracy","depth","clarity","structure","follow_up_stability"]}});const evalId=newId("eval");for(const x of res.output.observations??[]){if(x.targetType==="competency"&&this.catalog.has(x.competencyId))observations.push({schemaVersion:1,id:newId("obs"),evaluationId:evalId,semanticKey:`competency:${x.competencyId}`,timestamp:nowIso(),source:"real_feedback",target:{type:"competency",competencyId:x.competencyId},masterySignal:x.masterySignal??x.signal,evidenceStrength:x.evidenceStrength,confidence:x.confidence,summary:x.summary,evaluator:{name:"outcome-evaluator",model:res.model,promptVersion:"outcome-v1"}});else if(x.targetType==="interview_dimension"&&["technical_accuracy","depth","clarity","structure","follow_up_stability"].includes(x.dimension))observations.push({schemaVersion:1,id:newId("obs"),evaluationId:evalId,semanticKey:`interview:${x.dimension}`,timestamp:nowIso(),source:"real_feedback",target:{type:"interview_dimension",dimension:x.dimension},signal:x.signal,evidenceStrength:x.evidenceStrength,confidence:x.confidence,summary:x.summary,evaluator:{name:"outcome-evaluator",model:res.model,promptVersion:"outcome-v1"}});}if(res.output.experienceSummary)await this.ws.appendCareerExperience({schemaVersion:1,id:newId("career_event"),targetJobId:input.targetJobId,kind:"feedback",summary:String(res.output.experienceSummary),timestamp:nowIso()});}await this.updater.apply(observations);if(["offer","rejection","withdrawn"].includes(input.kind)){const svc=new TargetService(this.ws);await svc.transitionJob(input.targetJobId,input.kind==="rejection"?"rejected":input.kind as any);}return{observations:observations.length};}
}
